name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Log in to Private Docker Registry
      if: success()
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image latest
      if: success()
      run: docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/akogare-ng-websocket:latest .

    - name: Build Docker image version release
      if: success()
      run: docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/akogare-ng-websocket:0.0.1-RELEASE .
      
    - name: Push Docker image latest
      if: success()
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/akogare-ng-websocket:latest

    - name: Push Docker image version release
      if: success()
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/akogare-ng-websocket:0.0.1-RELEASE
      
    - name: Trigger Portainer Webhook
      if: success()
      run: curl -X POST ${{secrets.PORTAINER_AKOGARE_NG_WEBHOOK}}
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
